lmdb_path: dataset/latent.lmdb
batch_size: 1
num_workers: 0
epochs: 1
lr: 0.0001
weight_decay: 0.0001
log_interval: 10
video_interval: 1000
video_fps: 4
max_steps: 0
device: null
loss_mse_weight: 0.8
loss_mae_weight: 0.2
loss_scale: 20.0
wandb:
  project: nanogaia
  run_name: null
  disable: false
