lmdb_path: dataset/latent.lmdb
batch_size: 1
num_workers: 0
epochs: 1
lr: 0.0001
weight_decay: 0.0001
log_interval: 10
video_interval: 200
video_fps: 4
max_steps: 0
device: null
wandb:
  project: nanogaia
  run_name: null
  disable: false
